---

- name: Install supporting packages
  become: yes
  apt:
    name: "{{ item }}"
  with_items:
    - openjdk-7-jre-headless

- name: Add Logstash gpg key
  become: yes
  apt_key:
    url: https://packages.elasticsearch.org/GPG-KEY-elasticsearch
    state: present

- name: Install Logstash repo
  become: yes
  apt_repository:
    repo: "deb http://packages.elasticsearch.org/logstash/{{ elk_logstash.family }}/debian stable main"
    state: present

- name: Install Logstash
  become: yes
  apt:
    name: "logstash={{ elk_logstash.version }}"

- name: Install logstash plugins
  become: yes
  shell: "bin/plugin install {{ item }}"
  args:
    chdir: "/opt/logstash"
  with_items: elk_logstash.plugins
  notify:
    - restart logstash

- name: Enable logstash service
  become: yes
  service:
    name: logstash
    enabled: yes
  notify:
    - start logstash
